
DROP TABLE IF EXISTS TREATMENT;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS VOLUNTEER;

DROP TABLE IF EXISTS FAMILY;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS STATUS;
DROP TABLE IF EXISTS REQUESTCATEGORY;